services:
  - type: web
    name: predictive-maintenance
    env: python
    buildCommand: "pip install -r requirements.txt && chmod +x start.sh"
    startCommand: "./start.sh"
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
